### ISSUE TITLE
Website not reflective of latest code update

### ISSUE THREAD

**Issue by kevinjsaint** [immortius/gw2-wardrobe-unlock#13]
I have been using https://immortius.xyz/wardrobe-unlock-analyser/#about to try and collect everything for Wintersday and I noticed that wintergreen items there are only three listed items but I need the entire set. There has been recent changes to the code base but it looks like the website is behind. Can the website be updated or is the expectation that I take the source and run it on my own.

thanks

**Comment by immortius** [comment]
I think this is fixed now - I don't recall the exact circumstances but there was some disruption around the end of 2021 to my processes which have been smoothed out since. I don't know what code changes are being referenced - there were no code changes relating to wintergreen items prior to this issue I don't think?
